name: job_test
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.2
  bloc: ^9.0.0
  go_router: ^14.6.3
  intl: ^0.20.1
  fl_chart: ^0.70.2
  equatable: ^2.0.7
  flutter_bloc: ^9.0.0
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Semibold.ttf
    
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-Regular.ttf
        - asset: assets/fonts/Manrope-Medium.ttf